# QI Configuration file, see: https://github.com/amatas/vagrant-gpii-ci
---

env:
  vms:
    windows10:
      cpu: 2                   # number of cpus
      memory: 2048             # amount of RAM memory
      clone: true              # use the linked_clone Vagrant feature
      autostart: true
      box: inclusivedesign/windows10-eval-x64-Apps

stages:                # Stages to perform when 'ci test' command is invoked
  - setup              # Install our system-level dependencies, etc.
  - test               # Run the actual tests

setup_job:
  stage: setup
  script:
    - choco install nodejs-lts -y
    - choco install python2 -y

test_job:
  stage: test          # name of the stage
  script:              # One line per command to execute
    - "do.ps1 -c 'v: && npm install && npm test'"
